### ISSUE TITLE
Not all emojis appears in the list

### ISSUE THREAD

**Issue by gromain** [SebastianAigner/twemoji-amazing#1]
Hi,

I realized that when you generate the list, not all emojis appears. Specifically those where there is a dash in the name (like e-mail or t-shirt or yo-yo).

It appears the problem comes from this filter [here](https://github.com/SebastianAigner/twemoji-amazing/blob/master/src/main/kotlin/Main.kt#L17), that only checks if the name is made of letters or spaces.

Also, I stumbled upon the problem because I'm going to fork your repo and bring it to the Openmoji list. Thanks a lot for this!

**Comment by SebastianAigner** [comment]
Hi! I’m currently out of country without access to my development environment, but I’ll have a look and fix it once I’m back!

**Comment by gromain** [comment]
Sure, no worries! There's no hurry! Enjoy your holidays! :-D

**Comment by gromain** [comment]
Hi, just so you know, I couldn't directly fork your repo, but my fork is live here: https://github.com/gromain/openmoji-awesome
Please advise for attribution if current references are not enough!
Thanks a lot for your work on this project!

**Comment by gromain** [comment]
Just so you know, my fix to this introduced a bug where the country flags where not displayed anymore!

**Comment by SebastianAigner** [comment]
Hi! I’ll deploy a fix for this tomorrow.

**Comment by SebastianAigner** [comment]
Hi @gromain ! As promised, I've deployed a fix for twemoji-amazing. It now includes 3,005 emojis (according to their data, twemoji supports 3,075 emojis, but I think this'll cover most use cases!) Flags also work in my version, because I've gotten rid of the filtering logic altogether. I've instead introduced proper rewrite rules for special characters in descriptions.

Thanks again for reaching out and using twemoji-amazing!

Very cool that you forked the repository! I'm thinking that instead of duplicating the work, there's probably a way for us to support different configurations within the same project (even though the APIs look a little different from provider to provider). I'll consider support for openmoji in this generator as well at some point!
